name: coffeebudy
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase core (required for all Firebase services)
  firebase_core: ^3.15.2

  # Firebase Authentication
  firebase_auth: ^5.7.0

  # Cloud Firestore (database)
  cloud_firestore: ^5.6.12

  # Google Sign-In
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/google_logo.png

