// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbQVrWUmRKiidtvEMmcFczPpq7Moafomg',
    appId: '1:99245866277:web:343c5ba9f41ddcbfb76ecc',
    messagingSenderId: '99245866277',
    projectId: 'coffeebudy',
    authDomain: 'coffeebudy.firebaseapp.com',
    storageBucket: 'coffeebudy.firebasestorage.app',
    measurementId: 'G-8K2419E73Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUly5DI5sXQolhCTuU1Tur_3UtfTJVKtw',
    appId: '1:99245866277:android:5ff1fb3e80e5e1edb76ecc',
    messagingSenderId: '99245866277',
    projectId: 'coffeebudy',
    storageBucket: 'coffeebudy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqC0BVl6GWRDihpzbTzzTi0yacHchAC3k',
    appId: '1:99245866277:ios:af854e60038b3f0eb76ecc',
    messagingSenderId: '99245866277',
    projectId: 'coffeebudy',
    storageBucket: 'coffeebudy.firebasestorage.app',
    iosClientId: '99245866277-v6i2r8ua4176ah13miml5ai9r0q3jhu6.apps.googleusercontent.com',
    iosBundleId: 'com.coffeebudy.coffeebudy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqC0BVl6GWRDihpzbTzzTi0yacHchAC3k',
    appId: '1:99245866277:ios:af854e60038b3f0eb76ecc',
    messagingSenderId: '99245866277',
    projectId: 'coffeebudy',
    storageBucket: 'coffeebudy.firebasestorage.app',
    iosClientId: '99245866277-v6i2r8ua4176ah13miml5ai9r0q3jhu6.apps.googleusercontent.com',
    iosBundleId: 'com.coffeebudy.coffeebudy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbQVrWUmRKiidtvEMmcFczPpq7Moafomg',
    appId: '1:99245866277:web:7e81f9836bf53ef8b76ecc',
    messagingSenderId: '99245866277',
    projectId: 'coffeebudy',
    authDomain: 'coffeebudy.firebaseapp.com',
    storageBucket: 'coffeebudy.firebasestorage.app',
    measurementId: 'G-FBS2N2PYKV',
  );

}